baseURL = 'https://churningsheet.com'
languageCode = 'en-us'
title = 'ChurningSheet - Latest credit card and bank reward bonuses'
subtitle = "List of credit card and bank reward bonuses for churning. This sheet is constantly being updated."
theme = 'terminal'
keywords = 'credit card,bank,checking,savings,churning,bonus,rewards'
enableRobotsTXT = true
enableEmoji = true

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 0
  showLanguageSelector = false
  fullWidthTheme = true
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  favicon = "favicon.ico"

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    menuMore = "Show"
    readMore = "Read"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "ChurningSheet"
      logoHomeLink = "/"
